# Generated by Django 3.1.3 on 2021-01-03 22:25

import News_Sitesetting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=News_Sitesetting.models.upload_image_path_advers)),
                ('link', models.URLField(default='http://www.')),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to=News_Sitesetting.models.upload_image_path_contactImg)),
                ('msg', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('ntf', models.TextField()),
                ('is_simple', models.BooleanField(default=False)),
                ('is_specific', models.BooleanField(default=False)),
                ('is_newsTransition', models.BooleanField(default=False)),
                ('is_reporter', models.BooleanField(default=False)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('msg', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Send_Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('msg', models.TextField()),
                ('sended', models.BooleanField(default=False)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetiing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=20)),
                ('logo', models.ImageField(upload_to=News_Sitesetting.models.upload_image_path_logoWeb)),
                ('about_us', models.TextField()),
                ('about_website', models.TextField()),
                ('place_website', models.TextField()),
                ('telegram_id', models.URLField(blank=True, null=True)),
                ('whatsapp_id', models.URLField(blank=True, null=True)),
                ('instagram_id', models.URLField(blank=True, null=True)),
                ('scale_X', models.FloatField(default=0)),
                ('scale_Y', models.FloatField(default=0)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
